from enum import StrEnum


class System(StrEnum): JIRA = "JIRA"; GITHUB = "GITHUB"
class Domain(StrEnum): BUSINESS = "BUSINESS"; TECHNICAL = "TECHNICAL"; CROSS_DOMAIN = "CROSS_DOMAIN"
class ApprovalScope(StrEnum): BUSINESS = "BUSINESS"; TECHNICAL = "TECHNICAL"
class ArtifactKind(StrEnum): SPEC_PACKAGE = "SPEC_PACKAGE"; PROJECTION_PLAN = "PROJECTION_PLAN"; STATUS_POLICY = "STATUS_POLICY"
class PlanTarget(StrEnum): JIRA = "JIRA"; GITHUB = "GITHUB"
class JiraKind(StrEnum): EPIC = "EPIC"; STORY = "STORY"; TASK = "TASK"; SUBTASK = "SUBTASK"
class GitHubKind(StrEnum): ISSUE = "ISSUE"
class Action(StrEnum): CREATE = "CREATE"; UPDATE = "UPDATE"; RETIRE = "RETIRE"; TRANSITION_STATUS = "TRANSITION_STATUS"
class OperationStatus(StrEnum): PENDING = "PENDING"; FAILED = "FAILED"; UNKNOWN = "UNKNOWN"; SUCCEEDED = "SUCCEEDED"
class PackageState(StrEnum): DRAFT = "DRAFT"; READY = "READY"; APPROVED = "APPROVED"
class PlanState(StrEnum): READY = "READY"; APPROVED = "APPROVED"; APPLYING = "APPLYING"; APPLIED = "APPLIED"; STALE = "STALE"
class PolicyState(StrEnum): READY = "READY"; APPROVED = "APPROVED"
class JiraStatus(StrEnum): TODO = "TODO"; IN_PROGRESS = "IN_PROGRESS"; BLOCKED = "BLOCKED"; DONE = "DONE"; CANCELLED = "CANCELLED"; UNKNOWN = "UNKNOWN"
class GitHubStatus(StrEnum): OPEN = "OPEN"; CLOSED = "CLOSED"; UNKNOWN = "UNKNOWN"
class Lifecycle(StrEnum): ACTIVE = "ACTIVE"; RETIRED = "RETIRED"; UNKNOWN = "UNKNOWN"
class AmbiguityCategory(StrEnum):
    UNDEFINED_TERM = "UNDEFINED_TERM"; CONTRADICTION = "CONTRADICTION"; MISSING_OUTCOME = "MISSING_OUTCOME"
    UNBOUNDED_QUALIFIER = "UNBOUNDED_QUALIFIER"; MISSING_EDGE_CASE = "MISSING_EDGE_CASE"; MISSING_TECH_DECISION = "MISSING_TECH_DECISION"
class Severity(StrEnum): BLOCKING = "BLOCKING"; ADVISORY = "ADVISORY"
class FindingStatus(StrEnum): OPEN = "OPEN"; RESOLVED = "RESOLVED"
class FindingCategory(StrEnum):
    AMBIGUITY_UNRESOLVED = "AMBIGUITY_UNRESOLVED"; CONTENT_DRIFT = "CONTENT_DRIFT"; STALE_BINDING = "STALE_BINDING"
    STATUS_SYNC_REQUIRED = "STATUS_SYNC_REQUIRED"; STATUS_CONFLICT = "STATUS_CONFLICT"; MISSING_REMOTE_ITEM = "MISSING_REMOTE_ITEM"
    UNKNOWN_EXTERNAL_RESULT = "UNKNOWN_EXTERNAL_RESULT"; UNMAPPED_REMOTE_STATUS = "UNMAPPED_REMOTE_STATUS"
    TRACEABILITY_GAP = "TRACEABILITY_GAP"; LATER_REVIEW_REQUIRED = "LATER_REVIEW_REQUIRED"
class StatusConflictSubtype(StrEnum): MULTIPLE_TARGETS = "MULTIPLE_TARGETS"; MISSING_ITEM = "MISSING_ITEM"; INVALID_LIFECYCLE = "INVALID_LIFECYCLE"
class SetupStage(StrEnum): INTAKE = "INTAKE"; PACKAGE_REVIEW = "PACKAGE_REVIEW"; JIRA_REVIEW = "JIRA_REVIEW"; STATUS_REVIEW = "STATUS_REVIEW"; JIRA_APPLY = "JIRA_APPLY"; GITHUB_REVIEW = "GITHUB_REVIEW"; GITHUB_APPLY = "GITHUB_APPLY"; LINKED = "LINKED"
class WorkflowHealth(StrEnum): HEALTHY = "HEALTHY"; BLOCKED = "BLOCKED"
class DeliveryState(StrEnum): UNKNOWN = "UNKNOWN"; BLOCKED = "BLOCKED"; DONE = "DONE"; IN_PROGRESS = "IN_PROGRESS"; NOT_STARTED = "NOT_STARTED"
class SourceArtifactType(StrEnum): BUSINESS_SPEC = "BUSINESS_SPEC"; TECHNICAL_CONTRACT = "TECHNICAL_CONTRACT"; WORKSHOP_TRANSCRIPT = "WORKSHOP_TRANSCRIPT"; OTHER = "OTHER"
class Selector(StrEnum): ALL_PROJECTED_ITEMS = "ALL_PROJECTED_ITEMS"; IMPLEMENTATION_ITEMS = "IMPLEMENTATION_ITEMS"; ITEM_IDS = "ITEM_IDS"
class ConditionKind(StrEnum): PACKAGE_CURRENT_APPROVED = "PACKAGE_CURRENT_APPROVED"; NO_BLOCKING_FINDINGS = "NO_BLOCKING_FINDINGS"; JIRA_STATE_IN = "JIRA_STATE_IN"; GITHUB_STATE_IN = "GITHUB_STATE_IN"
class ObservationKind(StrEnum): FOUND = "FOUND"; NOT_FOUND = "NOT_FOUND"
class ResultOutcome(StrEnum): EXPLICIT_FAILURE = "EXPLICIT_FAILURE"; NOMINAL_SUCCESS = "NOMINAL_SUCCESS"
class TraceNodeKind(StrEnum):
    SOURCE_ARTIFACT = "SOURCE_ARTIFACT"; SPEC_PACKAGE = "SPEC_PACKAGE"; REQUIREMENT = "REQUIREMENT"
    TECHNICAL_DECISION = "TECHNICAL_DECISION"; ACCEPTANCE_CHECK = "ACCEPTANCE_CHECK"
    PROJECTION_PLAN = "PROJECTION_PLAN"; PROJECTION_ITEM = "PROJECTION_ITEM"
    EXTERNAL_BINDING = "EXTERNAL_BINDING"; STATUS_POLICY = "STATUS_POLICY"
class TraceEdgeType(StrEnum):
    SOURCE_TO_UNIT = "SOURCE_TO_UNIT"; PACKAGE_TO_UNIT = "PACKAGE_TO_UNIT"; UNIT_TO_JIRA_ITEM = "UNIT_TO_JIRA_ITEM"
    JIRA_PARENT = "JIRA_PARENT"; JIRA_DEPENDENCY = "JIRA_DEPENDENCY"; JIRA_ITEM_TO_BINDING = "JIRA_ITEM_TO_BINDING"
    JIRA_BINDING_TO_GITHUB_ITEM = "JIRA_BINDING_TO_GITHUB_ITEM"; GITHUB_ITEM_TO_BINDING = "GITHUB_ITEM_TO_BINDING"
    ITEM_TO_PACKAGE = "ITEM_TO_PACKAGE"; ITEM_TO_PLAN = "ITEM_TO_PLAN"
class EntityKind(StrEnum):
    AMBIGUITY_FINDING = "AMBIGUITY_FINDING"; PROJECTION_ITEM = "PROJECTION_ITEM"
    EXTERNAL_BINDING = "EXTERNAL_BINDING"; EXTERNAL_OPERATION = "EXTERNAL_OPERATION"
class ItemReadiness(StrEnum):
    FORMULATING = "FORMULATING"; NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"; READY = "READY"; BLOCKED = "BLOCKED"
class PackageReadiness(StrEnum):
    FORMULATING = "FORMULATING"; PARTIALLY_READY = "PARTIALLY_READY"; READY = "READY"; BLOCKED = "BLOCKED"
class ReviewObligation(StrEnum):
    NONE = "NONE"; LATER_REVIEW = "LATER_REVIEW"; DECISION_REQUIRED = "DECISION_REQUIRED"
class ReviewRequestKind(StrEnum): LATER_REVIEW = "LATER_REVIEW"; DECISION_REQUIRED = "DECISION_REQUIRED"
class ReviewRequestStatus(StrEnum): OPEN = "OPEN"; RESOLVED = "RESOLVED"
