from enum import StrEnum


class ErrorCode(StrEnum):
    RECORD_NOT_FOUND = "RECORD_NOT_FOUND"
    SYSTEM_ACTION_FORBIDDEN = "SYSTEM_ACTION_FORBIDDEN"
    AUTHORITY_REQUIRED = "AUTHORITY_REQUIRED"
    AUTHORITY_SLOT_OCCUPIED = "AUTHORITY_SLOT_OCCUPIED"
    DELEGATION_NOT_ACTIVE = "DELEGATION_NOT_ACTIVE"
    DELEGATION_SCOPE_MISMATCH = "DELEGATION_SCOPE_MISMATCH"
    APPROVAL_ALREADY_EXISTS = "APPROVAL_ALREADY_EXISTS"
    APPROVAL_BINDING_MISMATCH = "APPROVAL_BINDING_MISMATCH"
    STALE_ARTIFACT_BINDING = "STALE_ARTIFACT_BINDING"
    NO_SEMANTIC_CHANGE = "NO_SEMANTIC_CHANGE"
    INVALID_TRANSITION = "INVALID_TRANSITION"
    INVALID_SOURCE_REFERENCE = "INVALID_SOURCE_REFERENCE"
    INVALID_PROJECTION_PLAN = "INVALID_PROJECTION_PLAN"
    CROSS_CASE_REFERENCE = "CROSS_CASE_REFERENCE"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    OPERATION_RETRY_BLOCKED = "OPERATION_RETRY_BLOCKED"
    UNKNOWN_EXTERNAL_RESULT = "UNKNOWN_EXTERNAL_RESULT"
    UNCONFIRMED_EXTERNAL_ID = "UNCONFIRMED_EXTERNAL_ID"
    REMOTE_VERSION_MISMATCH = "REMOTE_VERSION_MISMATCH"
    STATUS_POLICY_NOT_APPROVED = "STATUS_POLICY_NOT_APPROVED"
    UNMAPPED_REMOTE_STATUS = "UNMAPPED_REMOTE_STATUS"
    BLOCKING_FINDING = "BLOCKING_FINDING"


class DomainError(Exception):
    def __init__(self, code: ErrorCode | str, message: str = "") -> None:
        self.code = ErrorCode(code)
        self.message = message or self.code.value
        super().__init__(self.message)

