from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

from specops_workshop.v4.api import create_contract_app


ROOT = Path(__file__).resolve().parents[2]


def test_openapi_publishes_strict_command_union_and_narrow_voice_operations():
    schema = create_contract_app().openapi()
    paths = schema["paths"]
    assert set(paths) == {
        "/api/v4/cases/{case_id}/artifact-review",
        "/api/v4/cases/{case_id}/artifacts/{artifact_type}",
        "/api/v4/cases/{case_id}/decision-review",
        "/api/v4/artifacts/{artifact_type}/synthesize",
        "/api/v4/artifacts/{artifact_type}/review",
        "/api/v4/artifacts/current/confirm",
        "/api/v4/decisions/current/respond",
        "/api/v4/foundation/commands",
        "/api/v4/voice/decision-responses",
        "/api/v4/voice/decision-selections",
        "/api/v4/voice/final-transcripts",
        "/api/v4/workshop/complete",
    }
    foundation = paths["/api/v4/foundation/commands"]["post"]["requestBody"]["content"]["application/json"]["schema"]
    assert len(foundation["oneOf"]) == 15
    assert foundation["discriminator"]["propertyName"] == "command_type"
    assert set(foundation["discriminator"]["mapping"]) == {
        "ACTIVATE_ANALYZER_CONTEXT",
        "INVALIDATE_ANALYZER_CONTEXT",
        "RECORD_FINAL_TRANSCRIPT",
        "CLAIM_WORKSHOP_COMPLETE",
        "ADMIT_INTERVIEW_BRIEF",
        "ADMIT_TURN_ANALYSIS",
        "ADMIT_GUIDANCE",
        "ADMIT_REVIEW_NARRATION",
        "ADMIT_SPEC_PACKAGE_SYNTHESIS",
        "ADMIT_TECHNICAL_CONTRACT_SYNTHESIS",
        "CAPTURE_LOW_RISK_FACT",
        "MATERIALIZE_DECISION_BATCH_REVIEW",
        "APPLY_DECISION_BATCH_RESPONSE",
        "MATERIALIZE_ARTIFACT_REVIEW",
        "CONFIRM_ARTIFACT",
    }
    components = schema["components"]["schemas"]
    for name in ("V4_RecordFinalTranscriptCommand", "V4_ApplyDecisionBatchResponseCommand"):
        assert components[name]["additionalProperties"] is False


def test_checked_in_openapi_and_typescript_are_generated_without_drift():
    result = subprocess.run(
        [
            sys.executable,
            "scripts/generate_v4_api_contracts.py",
            "--check",
        ],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    openapi_path = ROOT / "src/specops_workshop/v4/generated/openapi/workshop-v1.openapi.json"
    typescript_path = ROOT / "frontend/src/generated/workshopProtocol.ts"
    assert json.loads(openapi_path.read_text(encoding="utf-8"))["info"]["version"] == "1.0.0"
    typescript = typescript_path.read_text(encoding="utf-8")
    assert "This file was auto-generated by openapi-typescript" in typescript
    assert '"/api/v4/voice/final-transcripts"' in typescript
    assert "V4_ConfirmArtifactCommand" in typescript
